### ISSUE TITLE
The project is very interesting, thanks for publishing it, now I have a few questions

### ISSUE THREAD

**Issue by NickyDark1** [XuezheMax/megalodon#8]
How could I implement it with the huggingface models?

google colab for example?

thank you so much

**Comment by XuezheMax** [comment]
Thanks for your question.
The PyTorch module for each Megalodon block is here: https://github.com/XuezheMax/megalodon/blob/53cbaa3a3b3e05ea439564bd67cb352012ba6b97/megalodon/model/mega.py#L43
This repo includes all implementation details of the model. However, since some components are implemented by CUDA, you need to also move CUDA code to HuggingFace.
